services:
  royt-api-gateway:
    build:
      context: ./../api-gateway
      dockerfile: docker/Dockerfile.local
      args: # for dockerfile
        - PROJECT_NAME=$PROJECT_NAME
    # command: tail -f /dev/null
    command: ./manage.py runserver 0.0.0.0:8000
    volumes:
      - ./../api-gateway:/usr/src/api-gateway/
      - ${DATA_DIR}:/usr/data/
      - ${LOG_DIR}:/usr/log/
    ports:
      - ${BE_PORT}:8000
    env_file:
      - .env

  royt-frontend:
    build:
      context: ./../frontend
      dockerfile: docker/Dockerfile.local
      args:
        - PROJECT_NAME=$PROJECT_NAME
        - FE_PORT=${FE_PORT}
    command: sh -c "npm run dev -- --host 0.0.0.0"
    volumes:
      - ./../frontend:/usr/src/frontend
      - /usr/src/frontend/node_modules
    ports:
      - ${FE_PORT}:${FE_PORT}
    env_file:
      - .env
    environment:
      - VITE_API_BASE_URL=${BE_URL}/api
      - VITE_ENV=${RUNNING_ENV}
      - VITE_SERVICE_NAME=${SERVICE_NAME}
      - VITE_PORT=${FE_PORT}
    depends_on:
      - royt-api-gateway

volumes:
  static_volume:
  log:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /usr/log/
