# Generated by Django 3.2 on 2023-04-14 06:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('multipoly', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('center', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('geo_type', models.CharField(choices=[('PNU', 'Pnu'), ('MULTI_PNU', 'Multi Pnu'), ('SECTOR', 'Sector'), ('OTHERS', 'Others')], default='PNU', max_length=16)),
                ('주소_input', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('uniq_title', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('지번주소', models.CharField(blank=True, max_length=255, null=True)),
                ('도로명주소', models.CharField(blank=True, max_length=255, null=True)),
                ('pnu', models.CharField(blank=True, max_length=32, null=True)),
                ('시도', models.CharField(blank=True, max_length=32, null=True)),
                ('시군구', models.CharField(blank=True, max_length=32, null=True)),
                ('읍면동', models.CharField(blank=True, max_length=32, null=True)),
                ('산', models.BooleanField(blank=True, null=True)),
                ('본번', models.CharField(blank=True, max_length=4, null=True)),
                ('부번', models.CharField(blank=True, max_length=4, null=True)),
                ('지하', models.BooleanField(blank=True, null=True)),
                ('zone_no', models.CharField(blank=True, max_length=8, null=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('info_updated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('step1_gis_업데이트', models.BooleanField(default=False)),
                ('step1_gis_업데이트_at', models.DateTimeField(blank=True, null=True)),
                ('토지_count', models.PositiveSmallIntegerField(default=0)),
                ('건물_count', models.PositiveSmallIntegerField(default=0)),
                ('상가_count', models.PositiveSmallIntegerField(default=0)),
                ('total_물건_count', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
    ]
