# Generated by Django 3.2 on 2023-05-31 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geounit',
            options={},
        ),
        migrations.AddConstraint(
            model_name='geounit',
            constraint=models.UniqueConstraint(fields=('주소_input', 'uniq_title'), name='unique_geounit'),
        ),
    ]
