# Generated by Django 4.2 on 2025-10-20 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('channel_id', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='채널 ID')),
                ('channel_title', models.CharField(max_length=200, verbose_name='채널명')),
                ('channel_description', models.TextField(blank=True, verbose_name='채널 설명')),
                ('channel_custom_url', models.CharField(blank=True, max_length=100, verbose_name='채널 커스텀 URL')),
                ('channel_published_at', models.DateTimeField(blank=True, null=True, verbose_name='채널 생성일')),
                ('channel_thumbnail', models.URLField(blank=True, max_length=500, verbose_name='채널 썸네일')),
                ('channel_country', models.CharField(blank=True, max_length=10, verbose_name='국가')),
                ('subscriber_count', models.BigIntegerField(db_index=True, default=0, verbose_name='구독자 수')),
                ('video_count', models.BigIntegerField(default=0, verbose_name='영상 수')),
                ('view_count', models.BigIntegerField(db_index=True, default=0, verbose_name='총 조회수')),
                ('channel_keywords', models.TextField(blank=True, verbose_name='채널 키워드')),
            ],
            options={
                'verbose_name': 'YouTube 채널',
                'verbose_name_plural': 'YouTube 채널',
                'ordering': ['-subscriber_count', '-view_count'],
            },
        ),
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('video_id', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='비디오 ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('published_at', models.DateTimeField(db_index=True, verbose_name='게시일')),
                ('thumbnail_url', models.URLField(blank=True, max_length=500, verbose_name='썸네일')),
                ('view_count', models.BigIntegerField(db_index=True, default=0, verbose_name='조회수')),
                ('like_count', models.BigIntegerField(default=0, verbose_name='좋아요 수')),
                ('comment_count', models.BigIntegerField(default=0, verbose_name='댓글 수')),
                ('duration', models.CharField(blank=True, max_length=20, verbose_name='길이')),
                ('category_id', models.CharField(blank=True, db_index=True, max_length=10, verbose_name='카테고리 ID')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='태그')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='youtube.youtubechannel', verbose_name='채널')),
            ],
            options={
                'verbose_name': 'YouTube 영상',
                'verbose_name_plural': 'YouTube 영상',
                'ordering': ['-view_count', '-published_at'],
            },
        ),
        migrations.CreateModel(
            name='YouTubeVideoStatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('view_count', models.BigIntegerField(verbose_name='조회수')),
                ('like_count', models.BigIntegerField(verbose_name='좋아요 수')),
                ('comment_count', models.BigIntegerField(verbose_name='댓글 수')),
                ('snapshot_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='스냅샷 시각')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat_history', to='youtube.youtubevideo', verbose_name='영상')),
            ],
            options={
                'verbose_name': 'YouTube 영상 통계 히스토리',
                'verbose_name_plural': 'YouTube 영상 통계 히스토리',
                'ordering': ['-snapshot_at'],
            },
        ),
        migrations.AddIndex(
            model_name='youtubechannel',
            index=models.Index(fields=['-subscriber_count', '-view_count'], name='youtube_you_subscri_1229ac_idx'),
        ),
        migrations.AddIndex(
            model_name='youtubevideostathistory',
            index=models.Index(fields=['video', '-snapshot_at'], name='youtube_you_video_i_b1e0cf_idx'),
        ),
        migrations.AddIndex(
            model_name='youtubevideo',
            index=models.Index(fields=['-view_count', '-published_at'], name='youtube_you_view_co_3cf634_idx'),
        ),
        migrations.AddIndex(
            model_name='youtubevideo',
            index=models.Index(fields=['category_id', '-view_count'], name='youtube_you_categor_6643d5_idx'),
        ),
    ]
