# Generated by Django 4.2 on 2025-10-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='engagement_rate',
            field=models.FloatField(db_index=True, default=0.0, verbose_name='참여율 (%)'),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='youtube_url',
            field=models.URLField(blank=True, verbose_name='YouTube URL'),
        ),
        migrations.AddField(
            model_name='youtubevideostathistory',
            name='engagement_rate',
            field=models.FloatField(default=0.0, verbose_name='참여율 (%)'),
        ),
    ]
