# Generated by Django 4.2 on 2024-05-25 07:08

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Core',
            fields=[
                ('created_date', models.DateField(auto_now_add=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('gijun_date', models.DateField(blank=True, db_index=True, null=True)),
                ('gijun_date_str', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('center', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('원천도형ID', models.IntegerField(blank=True, null=True)),
                ('도면번호', models.CharField(blank=True, max_length=33, null=True)),
                ('주제도면', models.CharField(blank=True, max_length=254, null=True)),
                ('데이터기준일자', models.DateField(blank=True, null=True)),
                ('원천시도시군구코드', models.CharField(blank=True, max_length=5, null=True)),
                ('code', models.CharField(blank=True, db_index=True, max_length=8, null=True)),
                ('yongdo', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('yongdo_detail', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('is_indexed', models.BooleanField(db_index=True, default=False)),
                ('is_removed', models.BooleanField(db_index=True, default=False)),
                ('removed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Grid3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('grid2_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('cores', models.ManyToManyField(blank=True, db_index=True, to='log.core')),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CoreHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('gijun_date', models.DateField(blank=True, db_index=True, null=True)),
                ('gijun_date_str', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('center', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('원천도형ID', models.IntegerField(blank=True, null=True)),
                ('도면번호', models.CharField(blank=True, max_length=33, null=True)),
                ('주제도면', models.CharField(blank=True, max_length=254, null=True)),
                ('데이터기준일자', models.DateField(blank=True, null=True)),
                ('원천시도시군구코드', models.CharField(blank=True, max_length=5, null=True)),
                ('code', models.CharField(blank=True, db_index=True, max_length=8, null=True)),
                ('yongdo', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('yongdo_detail', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('is_indexed', models.BooleanField(db_index=True, default=False)),
                ('is_removed', models.BooleanField(db_index=True, default=False)),
                ('removed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('core', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_set', to='log.core')),
            ],
        ),
        migrations.AddConstraint(
            model_name='corehistory',
            constraint=models.UniqueConstraint(fields=('core', 'gijun_date_str'), name='ydjycore_unique_core_gijun_date_str'),
        ),
    ]
