# Generated by Django 3.2 on 2023-08-19 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20230810_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='article경기도',
            name='articleSubName',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='article경기도',
            name='cpName',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='article경기도',
            name='directTradeYN',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article경기도',
            name='duplexYN',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article경기도',
            name='floorInfo',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='article경기도',
            name='floorLayerName',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='article경기도',
            name='isComplex',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article경기도',
            name='isPriceModification',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article경기도',
            name='priceChangeState',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='article경기도',
            name='tradeCompleteYN',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article경기도',
            name='건물이름',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='article경기도',
            name='방갯수',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article경기도',
            name='총동갯수',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article경기도',
            name='추천업종',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='article경기도',
            name='현재용도',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='article경기도',
            name='화장실갯수',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article경기도history',
            name='articleSubName',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='article경기도history',
            name='cpName',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='article경기도history',
            name='directTradeYN',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article경기도history',
            name='duplexYN',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article경기도history',
            name='floorInfo',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='article경기도history',
            name='floorLayerName',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='article경기도history',
            name='isComplex',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article경기도history',
            name='isPriceModification',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article경기도history',
            name='priceChangeState',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='article경기도history',
            name='tradeCompleteYN',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article경기도history',
            name='건물이름',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='article경기도history',
            name='방갯수',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article경기도history',
            name='총동갯수',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article경기도history',
            name='추천업종',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='article경기도history',
            name='현재용도',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='article경기도history',
            name='화장실갯수',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        # manual doing
        # ALTER TABLE `core_article서울시` ADD COLUMN `articleSubName` varchar(64) NULL;
        migrations.AddField(
            model_name='article서울시',
            name='articleSubName',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='article서울시',
            name='cpName',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),

        ####################
        ###### 서울시 내일 여기부터
        migrations.AddField(
            model_name='article서울시',
            name='directTradeYN',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article서울시',
            name='duplexYN',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article서울시',
            name='floorInfo',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='article서울시',
            name='floorLayerName',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='article서울시',
            name='isComplex',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article서울시',
            name='isPriceModification',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article서울시',
            name='priceChangeState',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='article서울시',
            name='tradeCompleteYN',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article서울시',
            name='건물이름',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='article서울시',
            name='방갯수',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article서울시',
            name='총동갯수',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article서울시',
            name='추천업종',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='article서울시',
            name='현재용도',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='article서울시',
            name='화장실갯수',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article서울시history',
            name='articleSubName',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='article서울시history',
            name='cpName',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='article서울시history',
            name='directTradeYN',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article서울시history',
            name='duplexYN',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article서울시history',
            name='floorInfo',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='article서울시history',
            name='floorLayerName',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='article서울시history',
            name='isComplex',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article서울시history',
            name='isPriceModification',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article서울시history',
            name='priceChangeState',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='article서울시history',
            name='tradeCompleteYN',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article서울시history',
            name='건물이름',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='article서울시history',
            name='방갯수',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article서울시history',
            name='총동갯수',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article서울시history',
            name='추천업종',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='article서울시history',
            name='현재용도',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='article서울시history',
            name='화장실갯수',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article인천시',
            name='articleSubName',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='article인천시',
            name='cpName',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='article인천시',
            name='directTradeYN',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article인천시',
            name='duplexYN',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article인천시',
            name='floorInfo',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='article인천시',
            name='floorLayerName',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='article인천시',
            name='isComplex',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article인천시',
            name='isPriceModification',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article인천시',
            name='priceChangeState',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='article인천시',
            name='tradeCompleteYN',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article인천시',
            name='건물이름',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='article인천시',
            name='방갯수',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article인천시',
            name='총동갯수',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article인천시',
            name='추천업종',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='article인천시',
            name='현재용도',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='article인천시',
            name='화장실갯수',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article인천시history',
            name='articleSubName',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='article인천시history',
            name='cpName',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='article인천시history',
            name='directTradeYN',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article인천시history',
            name='duplexYN',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article인천시history',
            name='floorInfo',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='article인천시history',
            name='floorLayerName',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='article인천시history',
            name='isComplex',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article인천시history',
            name='isPriceModification',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article인천시history',
            name='priceChangeState',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='article인천시history',
            name='tradeCompleteYN',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article인천시history',
            name='건물이름',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='article인천시history',
            name='방갯수',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article인천시history',
            name='총동갯수',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField( # manual doing
            model_name='article인천시history',
            name='추천업종',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField( # manual doing
            model_name='article인천시history',
            name='현재용도',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='article인천시history',
            name='화장실갯수',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article경기도',
            name='type1',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='article경기도history',
            name='type1',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='article서울시',
            name='type1',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='article서울시history',
            name='type1',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='article인천시',
            name='type1',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='article인천시history',
            name='type1',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]

        # manual doing
        # ALTER TABLE `core_article인천시history` ADD COLUMN `articleSubName` varchar(64) NULL;