# Generated by Django 3.2 on 2023-09-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20230819_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article경기도',
            name='detail_processed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='article경기도history',
            name='detail_processed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='article서울시',
            name='detail_processed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='article서울시history',
            name='detail_processed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='article인천시',
            name='detail_processed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='article인천시history',
            name='detail_processed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
