# Generated by Django 3.2 on 2022-10-13 17:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_auto_20221011_0812'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubPrepared',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_date', models.DateField(auto_now_add=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(max_length=50)),
                ('point', models.PositiveSmallIntegerField(default=0)),
                ('chal_point', models.PositiveSmallIntegerField(default=0)),
                ('rank', models.PositiveSmallIntegerField(default=0)),
                ('chal_rank', models.PositiveSmallIntegerField(default=0)),
                ('kata_point', models.PositiveSmallIntegerField(default=0)),
                ('기준일', models.DateField(db_index=True)),
            ],
            options={
                'verbose_name': '클럽',
                'verbose_name_plural': '클럽',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerPrepared',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_date', models.DateField(auto_now_add=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('birthday', models.CharField(blank=True, default='000000', max_length=6, null=True)),
                ('main_club_str', models.CharField(max_length=50)),
                ('kata_point_ori_open', models.PositiveSmallIntegerField(default=0)),
                ('kata_point_ori_challenger', models.PositiveSmallIntegerField(default=0)),
                ('kata_point', models.PositiveSmallIntegerField(default=0)),
                ('point', models.PositiveSmallIntegerField(default=0)),
                ('is_challenger', models.BooleanField(default=False)),
                ('rank', models.PositiveSmallIntegerField(default=0)),
                ('image', models.URLField(blank=True, null=True)),
                ('기준일', models.DateField(db_index=True)),
            ],
            options={
                'verbose_name': '선수',
                'verbose_name_plural': '선수',
                'abstract': False,
            },
        ),
    ]
