# Generated by Django 3.2 on 2022-10-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_clubprepared_playerprepared'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubhistory',
            options={'verbose_name': '클럽(히스토리)', 'verbose_name_plural': '클럽(히스토리)'},
        ),
        migrations.AlterModelOptions(
            name='clubprepared',
            options={'verbose_name': '클럽(준비)', 'verbose_name_plural': '클럽(준비)'},
        ),
        migrations.AlterModelOptions(
            name='playerhistory',
            options={'verbose_name': '선수(히스토리)', 'verbose_name_plural': '선수(히스토리)'},
        ),
        migrations.AlterModelOptions(
            name='playerprepared',
            options={'verbose_name': '선수(준비)', 'verbose_name_plural': '선수(준비)'},
        ),
        migrations.AddField(
            model_name='clubhistory',
            name='기준일str',
            field=models.CharField(blank=None, default='20220101', max_length=8, null=None),
        ),
        migrations.AddField(
            model_name='clubprepared',
            name='기준일str',
            field=models.CharField(blank=None, default='20220101', max_length=8, null=None),
        ),
        migrations.AddField(
            model_name='playerhistory',
            name='기준일str',
            field=models.CharField(blank=None, default='20220101', max_length=8, null=None),
        ),
        migrations.AddField(
            model_name='playerprepared',
            name='기준일str',
            field=models.CharField(blank=None, default='20220101', max_length=8, null=None),
        ),
    ]
