# Generated by Django 3.2 on 2022-10-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_auto_20221015_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerhistory',
            name='is_challenger',
        ),
        migrations.RemoveField(
            model_name='playerprepared',
            name='is_challenger',
        ),
        migrations.AddField(
            model_name='playerhistory',
            name='player_level',
            field=models.CharField(choices=[('상급자부(남자)', '상급자부 남자'), ('신인부(남자)', '신인부 남자')], default='상급자부(남자)', max_length=32),
        ),
        migrations.AddField(
            model_name='playerprepared',
            name='player_level',
            field=models.CharField(choices=[('상급자부(남자)', '상급자부 남자'), ('신인부(남자)', '신인부 남자')], default='상급자부(남자)', max_length=32),
        ),
    ]
