# Generated by Django 3.2 on 2023-07-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawarticle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='count',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cluster',
            name='z',
            field=models.PositiveSmallIntegerField(default=14),
            preserve_default=False,
        ),
    ]
