# Generated by Django 3.2 on 2023-07-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawarticle', '0002_auto_20230727_0756'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtoArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('article_id', models.CharField(db_index=True, max_length=16)),
                ('lgeo', models.CharField(blank=True, max_length=16, null=True)),
                ('cortarNo', models.CharField(blank=True, max_length=16, null=True)),
                ('sido', models.CharField(blank=True, max_length=16, null=True)),
                ('sgg', models.CharField(blank=True, max_length=16, null=True)),
                ('emd', models.CharField(blank=True, max_length=16, null=True)),
                ('list_text', models.TextField()),
                ('url', models.URLField()),
                ('full_text', models.TextField()),
                ('has_text', models.BooleanField(default=False)),
                ('is_processed', models.BooleanField(db_index=True, default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('sel_text', models.TextField(blank=True, null=True)),
                ('is_sel_processed', models.BooleanField(db_index=True, default=False)),
                ('sel_processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='protoarticle',
            constraint=models.UniqueConstraint(fields=('article_id', 'created_date'), name='unique_article'),
        ),
    ]
