# Generated by Django 3.2 on 2023-07-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawarticle', '0004_cluster_article_collected_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionInstanceMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('region', models.CharField(db_index=True, max_length=16)),
                ('instance_id', models.CharField(db_index=True, max_length=16)),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
    ]
