# Generated by Django 3.2 on 2023-07-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawarticle', '0005_regioninstancemap'),
    ]

    operations = [
        migrations.AddField(
            model_name='regioninstancemap',
            name='aws_region',
            field=models.CharField(db_index=True, default='', max_length=16),
            preserve_default=False,
        ),
    ]
