# Generated by Django 3.2 on 2023-07-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawarticle', '0006_regioninstancemap_aws_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regioninstancemap',
            name='aws_region',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='regioninstancemap',
            name='instance_id',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='regioninstancemap',
            name='region',
            field=models.CharField(db_index=True, max_length=32),
        ),
    ]
