# Generated by Django 3.2 on 2023-07-30 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawarticle', '0008_auto_20230729_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='article_collection_end_time',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='article_collection_start_time',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0)),
        ),
    ]
