# Generated by Django 3.2 on 2023-08-01 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawarticle', '0012_blockedip_launch_time_when_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockedip',
            name='aws_region',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
    ]
