# Generated by Django 3.2 on 2023-08-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawarticle', '0015_auto_20230805_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCollectorTargetCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('us_east_1', models.PositiveSmallIntegerField(default=0)),
                ('us_east_2', models.PositiveSmallIntegerField(default=0)),
                ('us_west_1', models.PositiveSmallIntegerField(default=0)),
                ('us_west_2', models.PositiveSmallIntegerField(default=0)),
                ('ap_northeast_1', models.PositiveSmallIntegerField(default=0)),
                ('ap_northeast_2', models.PositiveSmallIntegerField(default=0)),
                ('ap_northeast_3', models.PositiveSmallIntegerField(default=0)),
                ('ap_southeast_1', models.PositiveSmallIntegerField(default=0)),
                ('ap_southeast_2', models.PositiveSmallIntegerField(default=0)),
                ('ap_south_1', models.PositiveSmallIntegerField(default=0)),
                ('ca_central_1', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArticleDetailCollectorTargetCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('us_east_1', models.PositiveSmallIntegerField(default=0)),
                ('us_east_2', models.PositiveSmallIntegerField(default=0)),
                ('us_west_1', models.PositiveSmallIntegerField(default=0)),
                ('us_west_2', models.PositiveSmallIntegerField(default=0)),
                ('ap_northeast_1', models.PositiveSmallIntegerField(default=0)),
                ('ap_northeast_2', models.PositiveSmallIntegerField(default=0)),
                ('ap_northeast_3', models.PositiveSmallIntegerField(default=0)),
                ('ap_southeast_1', models.PositiveSmallIntegerField(default=0)),
                ('ap_southeast_2', models.PositiveSmallIntegerField(default=0)),
                ('ap_south_1', models.PositiveSmallIntegerField(default=0)),
                ('ca_central_1', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstanceMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('aws_region', models.CharField(db_index=True, max_length=16)),
                ('stopped_instance_count', models.PositiveSmallIntegerField()),
                ('running_instance_count', models.PositiveSmallIntegerField()),
                ('pending_instance_count', models.PositiveSmallIntegerField()),
                ('terminated_instance_count', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='protoarticle',
            name='detail_processed_at',
        ),
        migrations.RemoveField(
            model_name='protoarticle',
            name='detail_text',
        ),
        migrations.RemoveField(
            model_name='protoarticle',
            name='has_detail_text',
        ),
        migrations.RemoveField(
            model_name='protoarticle',
            name='has_sel_text',
        ),
        migrations.RemoveField(
            model_name='protoarticle',
            name='is_detail_processed',
        ),
        migrations.RemoveField(
            model_name='protoarticle',
            name='is_sel_processed',
        ),
        migrations.RemoveField(
            model_name='protoarticle',
            name='sel_processed_at',
        ),
        migrations.RemoveField(
            model_name='protoarticle',
            name='sel_text',
        ),
    ]
