# Generated by Django 3.2 on 2023-08-08 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rawarticle', '0018_auto_20230808_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articledetailcollectortargetcount',
            name='ap_northeast_2',
        ),
    ]
