# Generated by Django 3.2 on 2023-08-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawarticle', '0020_baseimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseimage',
            name='security_group',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
