# Generated by Django 3.2 on 2023-08-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawarticle', '0021_baseimage_security_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseimage',
            name='instance_type',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
