# Generated by Django 3.2 on 2023-08-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawarticle', '0022_baseimage_instance_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseimage',
            name='key_name',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
