# Generated by Django 3.2 on 2023-08-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawarticle', '0023_baseimage_key_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseimage',
            name='region_alias',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
