# Generated by Django 3.2 on 2023-08-10 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rawarticle', '0025_cluster_done_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecollectortargetcount',
            name='ap_northeast_2',
        ),
    ]
