# Generated by Django 3.2 on 2023-08-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawarticle', '0026_remove_articlecollectortargetcount_ap_northeast_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='articledetailcollectortargetcount',
            name='eu_central_1',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articledetailcollectortargetcount',
            name='eu_north_1',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articledetailcollectortargetcount',
            name='eu_west_1',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articledetailcollectortargetcount',
            name='eu_west_2',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articledetailcollectortargetcount',
            name='eu_west_3',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articledetailcollectortargetcount',
            name='sa_east_1',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
