# Generated by Django 3.2 on 2023-08-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawarticle', '0027_auto_20230810_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecollectortargetcount',
            name='eu_central_1',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articlecollectortargetcount',
            name='eu_north_1',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articlecollectortargetcount',
            name='eu_west_1',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articlecollectortargetcount',
            name='eu_west_2',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articlecollectortargetcount',
            name='eu_west_3',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articlecollectortargetcount',
            name='sa_east_1',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
