# Generated by Django 3.2 on 2023-08-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawarticle', '0028_auto_20230810_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecollectortargetcount',
            name='af_south_1',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articlecollectortargetcount',
            name='ap_east_1',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articlecollectortargetcount',
            name='ap_south_2',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articlecollectortargetcount',
            name='ap_southeast_3',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articlecollectortargetcount',
            name='ap_southeast_4',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articlecollectortargetcount',
            name='eu_central_2',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articlecollectortargetcount',
            name='eu_south_1',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articlecollectortargetcount',
            name='eu_south_2',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articlecollectortargetcount',
            name='il_central_1',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articlecollectortargetcount',
            name='me_central_1',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articlecollectortargetcount',
            name='me_south_1',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
