# Generated by Django 3.2 on 2023-08-11 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawarticle', '0030_delete_cluster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('lgeo', models.CharField(db_index=True, max_length=16)),
                ('lat', models.CharField(max_length=16)),
                ('lon', models.CharField(max_length=16)),
                ('psr', models.CharField(max_length=16)),
                ('z', models.PositiveSmallIntegerField()),
                ('count', models.PositiveSmallIntegerField()),
                ('done_url', models.TextField(blank=True, null=True)),
                ('sido', models.CharField(blank=True, max_length=16, null=True)),
                ('sgg', models.CharField(blank=True, max_length=16, null=True)),
                ('emd', models.CharField(max_length=16)),
                ('parent', models.CharField(max_length=16)),
                ('is_collecting', models.BooleanField(default=False)),
                ('article_collection_start_time', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0))),
                ('article_collection_end_time', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0))),
                ('article_collected_date', models.DateField(db_index=True, default=datetime.datetime(1970, 1, 1, 0, 0))),
            ],
        ),
        migrations.AddConstraint(
            model_name='cluster',
            constraint=models.UniqueConstraint(fields=('lgeo', 'parent'), name='unique_cluster'),
        ),
    ]
