# Generated by Django 3.2 on 2023-08-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawarticle', '0032_auto_20230811_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='final_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
