###########
# BUILDER #
###########

# https://stackoverflow.com/questions/59554493/unable-to-fire-a-docker-build-for-django-and-mysql

# pull official base image
FROM python:3.7-slim as builder
MAINTAINER Intersources Inc.

RUN adduser app

# set work directory
WORKDIR /usr/src/backend

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY ./requirements.txt .
RUN pip install --upgrade pip
RUN pip wheel --no-cache-dir --no-deps --wheel-dir /usr/src/backend/wheels -r requirements.txt

#########
# FINAL #
#########

# pull official base image
FROM python:3.7-slim
MAINTAINER Intersources Inc.

# create directory for the app user
# RUN mkdir -p /home/app

# create the app user
RUN adduser app

# set timezone
ENV TZ Asia/Seoul

# create the appropriate directories
ENV HOME=/home/app
ENV APP_HOME=/home/app/web
RUN mkdir $APP_HOME
RUN mkdir $APP_HOME/staticfiles
WORKDIR $APP_HOME

RUN pip install --upgrade pip

# install dependencies

RUN apt-get update
COPY --from=builder /usr/src/backend/wheels /wheels
COPY --from=builder /usr/src/backend/requirements.txt .
RUN pip install --no-cache /wheels/*

RUN apt-get install python3-dev default-libmysqlclient-dev gcc  -y
RUN pip install mysqlclient

# copy entrypoint-dev.sh
COPY ./entrypoint.dev.sh $APP_HOME

# copy project
COPY . $APP_HOME

# chown all the files to the app user
RUN chown -R app:app $APP_HOME

# change to the app user
USER app

# CMD ["tail", "-f", "/dev/null"]
# run entrypoint.dev.sh
ENTRYPOINT ["/home/app/web/entrypoint.dev.bg_sample_command.sh"]