services:
  royt-api-gateway:
    build:
      context: ./../api-gateway
      dockerfile: docker/Dockerfile.local
      args: # for dockerfile
        - PROJECT_NAME=$PROJECT_NAME
    # command: tail -f /dev/null
    command: ./manage.py runserver 0.0.0.0:8000
    volumes:
      - ./../api-gateway:/usr/src/api-gateway/
      - ${DATA_DIR}:/usr/data/
      - ${LOG_DIR}:/usr/log/
    ports:
      - ${BE_PORT}:8000
    env_file:
      - .env

  #### 프론트 첫 설치시
  #### entrypoint.local.sh서에서 tail -f 로 넣고 들어가서 npm install
  ### 해야 함 : front$ mkdir -p ./node_modules/quasar/dist/ssr-directives/; cp ./docker/patch/* ./node_modules/quasar/dist/ssr-directives/

  # tojimetric-front:
  #   build:
  #     context: ./../front
  #     dockerfile: docker/Dockerfile.local
  #   # command: quasar dev -m ssr
  #   # command: quasar dev
  #   # command: tail -f /dev/null
  #   volumes:
  #     - ./../front:/usr/src/front/
  #     - ${DATA_DIR}:/usr/data/
  #     - ${LOG_DIR}:/usr/log/
  #   ports:
  #     - ${LOCAL_FE_PORT}:${LOCAL_FE_PORT}
  #     # - 24678:26878 # vite websocket for HMR?
  #   env_file:
  #     - .env
  #   restart: always

  # front-konsta:
  #   build:
  #     context: ./../front-konsta
  #     dockerfile: docker/Dockerfile.local
  #   # command: quasar dev -m ssr
  #   # command: quasar dev
  #   # command: tail -f /dev/null
  #   volumes:
  #     - ./../front-konsta:/usr/src/front-konsta/
  #     - ${DATA_DIR}:/usr/data/
  #     - ${LOG_DIR}:/usr/log/
  #   ports:
  #     - 7113:5173
  #     # - 24678:26878 # vite websocket for HMR?
  #   env_file:
  #     - .env
  #   restart: always

  # front-build: # 개발 서버에서처럼 빌드하고 싶을 때
  #   build:
  #     context: ./../front
  #     dockerfile: docker/Dockerfile.dev
  #   volumes:
  #     - ./../front:/usr/src/front/
  #   ports:
  #     - ${LOCAL_FE_PORT}:8080
  #     # - 24678:26878 # vite websocket for HMR?
  #   env_file:
  #     - .env
  #   restart: always

volumes:
  static_volume:
  log:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /usr/log/
