# Generated by Django 3.2 on 2023-08-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article경기도',
            name='has_history',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='article경기도history',
            name='has_history',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='article서울시',
            name='has_history',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='article서울시history',
            name='has_history',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='article인천시',
            name='has_history',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='article인천시history',
            name='has_history',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
