# Generated by Django 3.2 on 2023-08-10 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230810_0651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article서울시history',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='article인천시history',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Article경기도History',
        ),
        migrations.DeleteModel(
            name='Article서울시History',
        ),
        migrations.DeleteModel(
            name='Article인천시History',
        ),
    ]
