# Generated by Django 4.2 on 2024-02-29 16:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrontendVersion',
            fields=[
                ('created_date', models.DateField(auto_now_add=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('note', models.CharField(blank=True, db_index=True, max_length=255)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
