# Generated by Django 3.2 on 2022-10-09 22:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_date', models.DateField(auto_now_add=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('point', models.PositiveSmallIntegerField(default=0)),
                ('chal_point', models.PositiveSmallIntegerField(default=0)),
                ('rank', models.PositiveSmallIntegerField(default=0)),
                ('chal_rank', models.PositiveSmallIntegerField(default=0)),
                ('kata_point', models.PositiveSmallIntegerField(default=0)),
                ('기준일', models.DateField(db_index=True)),
                ('title', models.CharField(db_index=True, max_length=50, unique=True)),
                ('image', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '클럽',
                'verbose_name_plural': '클럽',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClubProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_date', models.DateField(auto_now_add=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('intro', models.CharField(blank=True, max_length=160, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_date', models.DateField(auto_now_add=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(default='기타', max_length=32)),
                ('comp_type', models.CharField(default='기타', max_length=16)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': '시합',
                'verbose_name_plural': '시합',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_date', models.DateField(auto_now_add=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('birthday', models.CharField(blank=True, default='000000', max_length=6, null=True)),
                ('main_club_str', models.CharField(max_length=50)),
                ('kata_point_ori_open', models.PositiveSmallIntegerField(default=0)),
                ('kata_point_ori_challenger', models.PositiveSmallIntegerField(default=0)),
                ('kata_point', models.PositiveSmallIntegerField(default=0)),
                ('total_point', models.PositiveSmallIntegerField(default=0)),
                ('is_challenger', models.BooleanField(default=False)),
                ('rank', models.PositiveSmallIntegerField(default=0)),
                ('image', models.URLField(blank=True, null=True)),
                ('기준일', models.DateField(db_index=True)),
                ('clubs', models.ManyToManyField(to='tenniscode.Club')),
            ],
            options={
                'verbose_name': '선수',
                'verbose_name_plural': '선수',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_date', models.DateField(auto_now_add=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('point_type', models.CharField(default='KATA', max_length=16)),
                ('result', models.CharField(max_length=16)),
                ('point', models.PositiveSmallIntegerField(default=0)),
                ('lt_point', models.PositiveSmallIntegerField(default=0)),
                ('match_date', models.DateField(db_index=True)),
                ('competition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CompetitionS_Performance', to='tenniscode.competition')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playerS_Performance', to='tenniscode.player')),
            ],
            options={
                'verbose_name': '성적',
                'verbose_name_plural': '성적',
            },
        ),
        migrations.AddConstraint(
            model_name='competition',
            constraint=models.UniqueConstraint(fields=('title', 'category'), name='unique title category'),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clubS_Profile', to='tenniscode.club'),
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(fields=('name', 'main_club_str'), name='unique name main_club_str'),
        ),
        migrations.AddConstraint(
            model_name='performance',
            constraint=models.UniqueConstraint(fields=('competition', 'player'), name='unique competition player'),
        ),
    ]
