# Generated by Django 3.2 on 2022-10-11 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenniscode', '0003_auto_20221010_2004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={},
        ),
    ]
