# Generated by Django 3.2 on 2022-10-13 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenniscode', '0005_preparedclub_preparedplayer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PreparedClub',
        ),
        migrations.DeleteModel(
            name='PreparedPlayer',
        ),
    ]
