# Generated by Django 3.2 on 2022-10-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenniscode', '0006_auto_20221013_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='기준일str',
            field=models.CharField(blank=None, default='20220101', max_length=8, null=None),
        ),
        migrations.AddField(
            model_name='player',
            name='기준일str',
            field=models.CharField(blank=None, default='20220101', max_length=8, null=None),
        ),
    ]
