# Generated by Django 3.2 on 2022-10-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenniscode', '0008_auto_20221016_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='prev_rank',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
