# Generated by Django 3.2 on 2022-10-25 19:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenniscode', '0011_club_prev_chal_rank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='kata_point',
            new_name='full_point',
        ),
        migrations.RenameField(
            model_name='club',
            old_name='point',
            new_name='full_rank',
        ),
        migrations.RenameField(
            model_name='club',
            old_name='prev_rank',
            new_name='master_point',
        ),
        migrations.RenameField(
            model_name='club',
            old_name='rank',
            new_name='master_rank',
        ),
        migrations.RemoveField(
            model_name='player',
            name='image',
        ),
        migrations.RemoveField(
            model_name='player',
            name='kata_point',
        ),
        migrations.RemoveField(
            model_name='player',
            name='kata_point_ori_challenger',
        ),
        migrations.RemoveField(
            model_name='player',
            name='kata_point_ori_open',
        ),
        migrations.AddField(
            model_name='club',
            name='prev_full_rank',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='club',
            name='prev_master_rank',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_date', models.DateField(auto_now_add=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('intro', models.CharField(blank=True, max_length=160, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playerS_Profile', to='tenniscode.player')),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
    ]
