# Generated by Django 3.2 on 2022-11-02 13:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenniscode', '0016_alter_clubprofile_club'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonClubComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_date', models.DateField(auto_now_add=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('content', models.TextField()),
                ('writer_name', models.CharField(max_length=255)),
                ('writer_ip', models.CharField(max_length=255)),
                ('writer_pw', models.CharField(max_length=16)),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ClubS_comments', to='tenniscode.club')),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
    ]
