# Generated by Django 3.2 on 2022-11-16 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenniscode', '0019_player_full_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonclubcomment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenniscode.anonclubcomment'),
        ),
    ]
