# Generated by Django 3.2 on 2022-11-20 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenniscode', '0020_anonclubcomment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonclubcomment',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ClubS_comments', to='tenniscode.club'),
        ),
    ]
