# Generated by Django 3.2 on 2023-07-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('created_date', models.DateField(auto_now_add=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('lgeo', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('lat', models.CharField(max_length=16)),
                ('lon', models.CharField(max_length=16)),
                ('psr', models.CharField(max_length=16)),
                ('sido', models.CharField(blank=True, max_length=16, null=True)),
                ('sgg', models.CharField(blank=True, max_length=16, null=True)),
                ('emd', models.CharField(max_length=16)),
                ('parent', models.CharField(max_length=16)),
                ('is_collecting', models.BooleanField(default=False)),
                ('article_collection_start_time', models.DateTimeField()),
                ('article_collection_end_time', models.DateTimeField()),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(max_length=16)),
                ('code', models.CharField(max_length=16)),
                ('cortarType', models.CharField(max_length=16)),
                ('regionType', models.CharField(db_index=True, max_length=8)),
                ('x', models.CharField(max_length=16)),
                ('y', models.CharField(max_length=16)),
                ('sido', models.CharField(blank=True, max_length=16, null=True)),
                ('sgg', models.CharField(blank=True, max_length=16, null=True)),
                ('emd', models.CharField(blank=True, max_length=16, null=True)),
                ('is_updated', models.BooleanField(default=False)),
                ('update_start_time', models.DateTimeField(blank=True, null=True)),
                ('update_end_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
    ]
