# Generated by Django 3.2 on 2023-07-27 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawarticle', '0003_auto_20230727_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='article_collected_date',
            field=models.DateField(db_index=True, default='1970-01-01'),
            preserve_default=False,
        ),
    ]
