# Generated by Django 3.2 on 2023-07-29 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawarticle', '0007_auto_20230729_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='regioninstancemap',
            name='launch_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 29, 20, 8, 42, 659448)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regioninstancemap',
            name='state',
            field=models.CharField(db_index=True, default='', max_length=16),
            preserve_default=False,
        ),
    ]
