# Generated by Django 3.2 on 2023-07-30 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawarticle', '0009_auto_20230730_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='article_collected_date',
            field=models.DateField(db_index=True, default=datetime.datetime(1970, 1, 1, 0, 0)),
        ),
    ]
