# Generated by Django 3.2 on 2023-07-31 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawarticle', '0011_blockedip'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockedip',
            name='launch_time_when_blocked',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
