# Generated by Django 3.2 on 2023-08-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawarticle', '0013_blockedip_aws_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protoarticle',
            name='full_text',
        ),
        migrations.RemoveField(
            model_name='protoarticle',
            name='has_text',
        ),
        migrations.RemoveField(
            model_name='protoarticle',
            name='url',
        ),
        migrations.AddField(
            model_name='protoarticle',
            name='has_sel_text',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
