# Generated by Django 3.2 on 2023-08-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawarticle', '0014_auto_20230805_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='protoarticle',
            name='detail_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protoarticle',
            name='detail_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protoarticle',
            name='has_detail_text',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='protoarticle',
            name='is_detail_processed',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
