# Generated by Django 3.2 on 2023-08-08 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rawarticle', '0016_auto_20230808_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instancemonitoring',
            name='aws_region',
        ),
    ]
