# Generated by Django 3.2 on 2023-08-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawarticle', '0017_remove_instancemonitoring_aws_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instancemonitoring',
            name='pending_instance_count',
        ),
        migrations.RemoveField(
            model_name='instancemonitoring',
            name='running_instance_count',
        ),
        migrations.RemoveField(
            model_name='instancemonitoring',
            name='stopped_instance_count',
        ),
        migrations.RemoveField(
            model_name='instancemonitoring',
            name='terminated_instance_count',
        ),
        migrations.AddField(
            model_name='instancemonitoring',
            name='pending',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='instancemonitoring',
            name='running',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='instancemonitoring',
            name='shutting_down',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='instancemonitoring',
            name='stopped',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='instancemonitoring',
            name='stopping',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='instancemonitoring',
            name='terminated',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
