# Generated by Django 3.2 on 2023-08-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawarticle', '0024_baseimage_region_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='done_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
