# Generated by Django 3.2 on 2023-08-11 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rawarticle', '0029_auto_20230810_2038'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cluster',
        ),
    ]
