# Generated by Django 3.2 on 2023-08-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawarticle', '0033_cluster_final_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseimage',
            name='detail_image_name',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
