# Generated by Django 3.2 on 2023-08-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawarticle', '0034_baseimage_detail_image_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleDetailCollectorControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('percent', models.PositiveSmallIntegerField(default=10)),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ArticleDetailCollectorTargetCount',
        ),
    ]
