# Generated by Django 3.2 on 2023-08-11 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rawarticle', '0035_auto_20230811_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseimage',
            name='detail_image_name',
        ),
    ]
