# Generated by Django 3.2 on 2022-10-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubhistory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='playerhistory',
            options={},
        ),
        migrations.AddConstraint(
            model_name='clubhistory',
            constraint=models.UniqueConstraint(fields=('title', '기준일'), name='unique title 기준일'),
        ),
        migrations.AddConstraint(
            model_name='playerhistory',
            constraint=models.UniqueConstraint(fields=('name', 'main_club_str', '기준일'), name='unique name main_club_str 기준일'),
        ),
    ]
