# Generated by Django 3.2 on 2022-10-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0005_auto_20221016_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubhistory',
            old_name='kata_point',
            new_name='full_point',
        ),
        migrations.RenameField(
            model_name='clubhistory',
            old_name='point',
            new_name='full_rank',
        ),
        migrations.RenameField(
            model_name='clubhistory',
            old_name='rank',
            new_name='master_point',
        ),
        migrations.RenameField(
            model_name='clubprepared',
            old_name='kata_point',
            new_name='full_point',
        ),
        migrations.RenameField(
            model_name='clubprepared',
            old_name='point',
            new_name='full_rank',
        ),
        migrations.RenameField(
            model_name='clubprepared',
            old_name='rank',
            new_name='master_point',
        ),
        migrations.RemoveField(
            model_name='playerhistory',
            name='image',
        ),
        migrations.RemoveField(
            model_name='playerhistory',
            name='kata_point',
        ),
        migrations.RemoveField(
            model_name='playerhistory',
            name='kata_point_ori_challenger',
        ),
        migrations.RemoveField(
            model_name='playerhistory',
            name='kata_point_ori_open',
        ),
        migrations.RemoveField(
            model_name='playerprepared',
            name='image',
        ),
        migrations.RemoveField(
            model_name='playerprepared',
            name='kata_point',
        ),
        migrations.RemoveField(
            model_name='playerprepared',
            name='kata_point_ori_challenger',
        ),
        migrations.RemoveField(
            model_name='playerprepared',
            name='kata_point_ori_open',
        ),
        migrations.AddField(
            model_name='clubhistory',
            name='master_rank',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clubprepared',
            name='master_rank',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
