# Generated by Django 3.2 on 2022-10-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0006_auto_20221025_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerhistory',
            old_name='point',
            new_name='challenger_point',
        ),
        migrations.RenameField(
            model_name='playerprepared',
            old_name='point',
            new_name='challenger_point',
        ),
        migrations.AddField(
            model_name='playerhistory',
            name='master_point',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerprepared',
            name='master_point',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerhistory',
            name='player_level',
            field=models.CharField(choices=[('상급자부(남자)', '상급자부 남자'), ('신인부(남자)', '신인부 남자')], max_length=32),
        ),
        migrations.AlterField(
            model_name='playerprepared',
            name='player_level',
            field=models.CharField(choices=[('상급자부(남자)', '상급자부 남자'), ('신인부(남자)', '신인부 남자')], max_length=32),
        ),
    ]
