# Generated by Django 3.2 on 2022-10-27 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0007_auto_20221027_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubhistory',
            old_name='chal_rank',
            new_name='challenger_rank',
        ),
        migrations.RenameField(
            model_name='clubprepared',
            old_name='chal_rank',
            new_name='challenger_rank',
        ),
    ]
