# Generated by Django 3.2 on 2022-10-28 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0008_auto_20221027_1916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubhistory',
            old_name='chal_point',
            new_name='challenger_point',
        ),
        migrations.RenameField(
            model_name='clubprepared',
            old_name='chal_point',
            new_name='challenger_point',
        ),
    ]
