# Generated by Django 3.2 on 2022-11-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0009_auto_20221028_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerhistory',
            name='full_point',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerprepared',
            name='full_point',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
