# Generated by Django 3.2 on 2022-12-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0010_auto_20221109_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubhistory',
            name='players_count_having_performance',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clubprepared',
            name='players_count_having_performance',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
