# Generated by Django 3.2 on 2023-08-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('proto_article_collected_today', models.PositiveIntegerField()),
                ('proto_article_processed_today', models.PositiveIntegerField()),
                ('서울시_created_today', models.PositiveIntegerField()),
                ('서울시_updated_today', models.PositiveIntegerField()),
                ('서울시_has_detail', models.PositiveIntegerField()),
                ('서울시_is_detail_processed', models.PositiveIntegerField()),
                ('서울시_is_detail_failed', models.PositiveIntegerField()),
                ('서울시_is_pnu_processed', models.PositiveIntegerField()),
                ('경기도_created_today', models.PositiveIntegerField()),
                ('경기도_updated_today', models.PositiveIntegerField()),
                ('경기도_has_detail', models.PositiveIntegerField()),
                ('경기도_is_detail_processed', models.PositiveIntegerField()),
                ('경기도_is_detail_failed', models.PositiveIntegerField()),
                ('경기도_is_pnu_processed', models.PositiveIntegerField()),
                ('인천시_created_today', models.PositiveIntegerField()),
                ('인천시_updated_today', models.PositiveIntegerField()),
                ('인천시_has_detail', models.PositiveIntegerField()),
                ('인천시_is_detail_processed', models.PositiveIntegerField()),
                ('인천시_is_detail_failed', models.PositiveIntegerField()),
                ('인천시_is_pnu_processed', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
    ]
