# Generated by Django 3.2 on 2023-08-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_auto_20230812_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='경기도_total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='서울시_total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='인천시_total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
