# Generated by Django 3.2 on 2023-08-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_auto_20230812_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='경기도_has_detail_gap',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='서울시_has_detail_gap',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='인천시_has_detail_gap',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
