# Generated by Django 3.2 on 2023-08-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_auto_20230813_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='경기도_is_pnu_not_null',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='서울시_is_pnu_not_null',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='인천시_is_pnu_not_null',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
