# Generated by Django 3.2 on 2023-08-15 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_auto_20230815_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='경기도_is_pnu_not_null',
            new_name='경기도_is_pnu_null',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='서울시_is_pnu_not_null',
            new_name='서울시_is_pnu_null',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='인천시_is_pnu_not_null',
            new_name='인천시_is_pnu_null',
        ),
    ]
