# Generated by Django 3.2 on 2022-10-09 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenniscode', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='total_point',
            new_name='point',
        ),
    ]
