# Generated by Django 3.2 on 2022-10-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenniscode', '0002_rename_total_point_player_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='image',
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
