# Generated by Django 3.2 on 2022-10-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenniscode', '0010_club_prev_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='prev_chal_rank',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
