# Generated by Django 3.2 on 2022-10-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenniscode', '0012_auto_20221025_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='point',
            new_name='challenger_point',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='lt_point',
        ),
        migrations.AddField(
            model_name='performance',
            name='performance_level',
            field=models.CharField(choices=[('상급자부(남자)', '상급자부 남자'), ('신인부(남자)', '신인부 남자')], default=None, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='master_point',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_level',
            field=models.CharField(choices=[('상급자부(남자)', '상급자부 남자'), ('신인부(남자)', '신인부 남자')], max_length=32),
        ),
    ]
