# Generated by Django 3.2 on 2022-11-01 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenniscode', '0015_rename_chal_point_club_challenger_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubprofile',
            name='club',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenniscode.club'),
        ),
    ]
