# Generated by Django 3.2 on 2022-11-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenniscode', '0017_anonclubcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='is_effective',
            field=models.BooleanField(default=False),
        ),
    ]
