# Generated by Django 3.2 on 2022-11-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenniscode', '0018_performance_is_effective'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='full_point',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
