# Generated by Django 3.2 on 2022-11-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenniscode', '0022_auto_20221120_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonclubcomment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
