# Generated by Django 3.2 on 2022-12-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenniscode', '0023_anonclubcomment_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='players_count_having_performance',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
