# Generated by Django 4.2 on 2025-10-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_youtubevideo_engagement_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideostathistory',
            name='original_saved_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='원본 데이터 저장 시각'),
        ),
        migrations.AlterField(
            model_name='youtubevideostathistory',
            name='snapshot_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='히스토리 저장 시각'),
        ),
    ]
