# Generated by Django 4.2 on 2025-10-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0003_youtubevideostathistory_original_saved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='views_per_subscriber',
            field=models.FloatField(db_index=True, default=0.0, verbose_name='구독자 대비 조회수 (%)'),
        ),
        migrations.AddField(
            model_name='youtubevideostathistory',
            name='views_per_subscriber',
            field=models.FloatField(default=0.0, verbose_name='구독자 대비 조회수 (%)'),
        ),
    ]
