# Generated by Django 4.2 on 2025-10-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0004_youtubevideo_views_per_subscriber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubechannel',
            name='uploads_playlist_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='업로드 플레이리스트 ID'),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='views_per_subscriber',
            field=models.FloatField(db_index=True, default=0.0, verbose_name='구독자 대비 조회수 (배수)'),
        ),
        migrations.AlterField(
            model_name='youtubevideostathistory',
            name='views_per_subscriber',
            field=models.FloatField(default=0.0, verbose_name='구독자 대비 조회수 (배수)'),
        ),
    ]
