# Generated by Django 4.2 on 2025-10-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0005_youtubechannel_uploads_playlist_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='transcript',
            field=models.TextField(blank=True, verbose_name='자막 (전체 텍스트)'),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='transcript_language',
            field=models.CharField(blank=True, max_length=10, verbose_name='자막 언어 코드'),
        ),
    ]
