# Generated by Django 4.2 on 2025-10-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0007_youtubevideo_transcript_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='refined_transcript',
            field=models.TextField(blank=True, verbose_name='정리된 자막 (AI 수정)'),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='refined_transcript_status',
            field=models.CharField(blank=True, db_index=True, help_text='pending: 대기, processing: 처리 중, completed: 완료, failed: 실패', max_length=20, verbose_name='자막 정리 상태'),
        ),
    ]
