# Generated by Django 4.2 on 2025-10-24 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0008_youtubevideo_refined_transcript_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubevideo',
            name='refined_transcript',
        ),
        migrations.RemoveField(
            model_name='youtubevideo',
            name='refined_transcript_status',
        ),
        migrations.RemoveField(
            model_name='youtubevideo',
            name='transcript',
        ),
        migrations.RemoveField(
            model_name='youtubevideo',
            name='transcript_language',
        ),
        migrations.RemoveField(
            model_name='youtubevideo',
            name='transcript_status',
        ),
    ]
