# Generated by Django 4.2 on 2025-10-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0009_remove_youtubevideo_refined_transcript_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='transcript',
            field=models.TextField(blank=True, verbose_name='자막 (전체 텍스트)'),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='transcript_language',
            field=models.CharField(blank=True, max_length=10, verbose_name='자막 언어 코드'),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='transcript_status',
            field=models.CharField(blank=True, db_index=True, help_text='success: 성공, no_transcript: 자막 없음, disabled: 비활성화, unavailable: 비디오 사용 불가, error: 기타 오류', max_length=20, verbose_name='자막 조회 상태'),
        ),
    ]
