# Generated by Django 4.2 on 2025-10-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0010_youtubevideo_transcript_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubechannel',
            name='is_excluded',
            field=models.BooleanField(db_index=True, default=False, help_text='True로 설정하면 인기 급상승 영상 수집 시 이 채널의 영상을 제외합니다', verbose_name='수집 제외 여부'),
        ),
    ]
