# Generated by Django 4.2 on 2025-10-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0011_youtubechannel_is_excluded'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeVideoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('category_id', models.CharField(max_length=10, verbose_name='카테고리 ID')),
                ('category_title', models.CharField(max_length=100, verbose_name='카테고리 이름')),
                ('assignable', models.BooleanField(default=True, verbose_name='영상 할당 가능 여부')),
                ('region_code', models.CharField(db_index=True, max_length=2, verbose_name='국가 코드')),
            ],
            options={
                'verbose_name': 'YouTube 비디오 카테고리',
                'verbose_name_plural': 'YouTube 비디오 카테고리',
                'ordering': ['region_code', 'category_id'],
            },
        ),
        migrations.AddIndex(
            model_name='youtubevideocategory',
            index=models.Index(fields=['region_code', 'category_id'], name='youtube_you_region__f76785_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='youtubevideocategory',
            unique_together={('category_id', 'region_code')},
        ),
    ]
