# Generated by Django 4.2 on 2024-05-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usercustom'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='theme_colors',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
