# Generated by Django 4.2 on 2024-05-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_usercustom_theme_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercustom',
            name='theme_colors',
        ),
        migrations.AddField(
            model_name='usercustom',
            name='theme_colors_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
