# Generated by Django 3.2 on 2023-08-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_auto_20230812_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleProto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('proto_article_created_today', models.PositiveIntegerField(blank=True, null=True)),
                ('proto_article_processed_today', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='article',
            name='proto_article_collected_today',
        ),
        migrations.RemoveField(
            model_name='article',
            name='proto_article_processed_today',
        ),
    ]
