# Generated by Django 3.2 on 2023-08-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_auto_20230812_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='경기도_NOT_has_detail_created_today',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='경기도_has_detail_created_today',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='서울시_NOT_has_detail_created_today',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='서울시_has_detail_created_today',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='인천시_NOT_has_detail_created_today',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='인천시_has_detail_created_today',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
