# Generated by Django 3.2 on 2022-10-09 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rticler', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='temp_article',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rticler.temparticle'),
        ),
    ]
