# Generated by Django 3.2 on 2023-09-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('fullname', models.CharField(db_index=True, max_length=64)),
                ('sido', models.CharField(db_index=True, max_length=16)),
                ('sgg', models.CharField(db_index=True, max_length=16)),
                ('emd', models.CharField(db_index=True, max_length=16)),
                ('gijun_date', models.DateField(blank=True, db_index=True, null=True)),
                ('gijun_date_str', models.CharField(blank=True, db_index=True, max_length=16, null=True)),
                ('proto_created_count', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
    ]
